name: 'Caliptra Security Scanner'
description: 'Security scanning for repositories using Caliptra'

inputs:
  github_context:
    description: 'GitHub context object from the workflow'
    required: true
  inputs_context:
    description: 'Inputs context object from the workflow'
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Container registry
      shell: bash
      run: |
        echo "${{ fromJSON(inputs.github_context).token }}" | docker login ghcr.io \
          -u ${{ fromJSON(inputs.github_context).actor }} --password-stdin
          
    # - name: Check Inputs
    #   shell: bash
    #   run: echo "${{ toJSON(fromJSON(inputs.github_context)) }}"

    - name: Pull scanner image
      shell: bash
      run: docker pull ghcr.io/caliptrasecurity/agent:main

    - name: Run Dependency Scanner
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ inputs.github_context }}
        INPUTS_CONTEXT: ${{ inputs.inputs_context }}
      run: |
        docker run --rm \
          -v ${{ fromJSON(inputs.github_context).workspace }}:/code \
          -e SCAN_PATH=/code \
          -e INPUT_FAIL_ON_SEVERITY=true \
          -e GITHUB_TOKEN=${{ fromJSON(inputs.github_context).token }} \
          -e GITHUB_REF_NAME="$ref_name" \
          -e GITHUB_SHA="$sha" \
          -e GITHUB_REPOSITORY="$repository" \
          -e GITHUB_REPOSITORY_ID="${{ fromJSON(inputs.github_context).repository_id }}" \
          -e GITHUB_EVENT_NAME="$event_name" \
          -e CLIENT_PAYLOAD="$client_payload" \
          -e GITHUB_REPOSITORY_NAME="${{ fromJSON(inputs.github_context).repository }}" \
          ghcr.io/caliptrasecurity/agent:main
